# Generated by Django 4.1.4 on 2023-06-16 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 6, 16, 14, 46, 31, 265059)),
        ),
    ]
