# Generated by Django 4.1.4 on 2023-06-18 04:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_photo_options_profile_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 6, 18, 4, 31, 12, 682831, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='follow_table', serialize=False, to='base.profile')),
                ('following', models.ManyToManyField(related_name='followers', to='base.profile')),
            ],
        ),
    ]
