# Generated by Django 4.1.4 on 2023-06-18 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_profile_following_alter_post_upload_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 6, 18, 4, 32, 33, 725941, tzinfo=datetime.timezone.utc)),
        ),
    ]
