# Generated by Django 4.1.4 on 2023-06-18 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_post_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
