# Generated by Django 4.1.4 on 2023-06-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_message_upload_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-upload_time']},
        ),
    ]
